-- =====================================================================
-- Enterprise Text-to-SQL — database schema (DDL)
--
-- Phase 1, Task 1.2. Structure only, no data.
--
-- Usage (from project root):
--   psql -U texttosql_app -d enterprise_sql -f database/schema.sql
--   env\Scripts\python.exe scripts/load_schema.py
--
-- !! THIS FILE DROPS AND RECREATES EVERY TABLE. All data is lost. !!
--
-- That is deliberate. The schema changes often during Phases 1-3, and a
-- reproducible rebuild matters more than preserving throwaway synthetic
-- data. The database is disposable; this file is the source of truth.
-- Bulk data is regenerated by scripts/generate_data.py.
--
-- Conventions (see database/README.md):
--   tables      snake_case, plural          customers, order_items
--   columns     snake_case, singular        customer_id, total_amount
--   PK          <singular_table>_id         customers.customer_id
--   FK          same name as referenced PK  orders.customer_id
--   timestamps  TIMESTAMPTZ                 never naive TIMESTAMP
--   money       NUMERIC(12, 2)              never FLOAT
--   constraints explicitly named            fk_orders_customer
-- =====================================================================

BEGIN;

-- ---------------------------------------------------------------------
-- Drop in reverse dependency order. CASCADE is not used: explicit order
-- means an unexpected dependency surfaces as an error instead of being
-- silently dropped along with something else.
-- ---------------------------------------------------------------------
DROP TABLE IF EXISTS shipments;
DROP TABLE IF EXISTS payments;
DROP TABLE IF EXISTS order_items;
DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS inventory;
DROP TABLE IF EXISTS products;
DROP TABLE IF EXISTS customers;
DROP TABLE IF EXISTS employees;
DROP TABLE IF EXISTS departments;
DROP TABLE IF EXISTS warehouses;
DROP TABLE IF EXISTS suppliers;
DROP TABLE IF EXISTS categories;


-- =====================================================================
-- SECTION 1 — Reference tables
-- No outbound foreign keys (except self-references). Created first.
-- =====================================================================

-- Product categories, self-referencing to form a hierarchy:
-- 'Electronics' -> 'Laptops' -> 'Gaming Laptops'.
-- The hierarchy is what makes recursive-CTE benchmark questions possible.
CREATE TABLE categories (
    category_id         SERIAL       PRIMARY KEY,
    category_name       VARCHAR(100) NOT NULL,
    parent_category_id  INTEGER,
    description         TEXT,
    created_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_categories_name UNIQUE (category_name),
    CONSTRAINT fk_categories_parent
        FOREIGN KEY (parent_category_id) REFERENCES categories (category_id),
    -- A category cannot be its own parent. Does not prevent longer cycles
    -- (A->B->A); the data generator is responsible for that.
    CONSTRAINT chk_categories_not_self_parent
        CHECK (parent_category_id IS DISTINCT FROM category_id)
);

CREATE TABLE suppliers (
    supplier_id     SERIAL       PRIMARY KEY,
    supplier_name   VARCHAR(200) NOT NULL,
    contact_name    VARCHAR(150),
    contact_email   VARCHAR(255),
    phone           VARCHAR(40),
    country         VARCHAR(100) NOT NULL,
    city            VARCHAR(100),
    -- Supplier quality score, used for business-rule questions
    -- ("suppliers rated below 3"). Nullable: not every supplier is rated.
    rating          NUMERIC(3, 2),
    is_active       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_suppliers_name UNIQUE (supplier_name),
    CONSTRAINT chk_suppliers_rating_range
        CHECK (rating IS NULL OR rating BETWEEN 0 AND 5),
    CONSTRAINT chk_suppliers_email_format
        CHECK (contact_email IS NULL OR contact_email LIKE '%_@_%.__%')
);

CREATE TABLE warehouses (
    warehouse_id    SERIAL       PRIMARY KEY,
    warehouse_name  VARCHAR(150) NOT NULL,
    country         VARCHAR(100) NOT NULL,
    city            VARCHAR(100) NOT NULL,
    -- Maximum storage units. Enables "warehouses above 80% capacity".
    capacity_units  INTEGER      NOT NULL,
    is_active       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_warehouses_name UNIQUE (warehouse_name),
    CONSTRAINT chk_warehouses_capacity_positive CHECK (capacity_units > 0)
);

CREATE TABLE departments (
    department_id    SERIAL        PRIMARY KEY,
    department_name  VARCHAR(100)  NOT NULL,
    location         VARCHAR(150),
    annual_budget    NUMERIC(14, 2),
    created_at       TIMESTAMPTZ   NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_departments_name UNIQUE (department_name),
    CONSTRAINT chk_departments_budget_non_negative
        CHECK (annual_budget IS NULL OR annual_budget >= 0)
);


-- =====================================================================
-- SECTION 2 — Core entities
-- =====================================================================

-- Self-referencing via manager_id to form a reporting chain.
-- The CEO's manager_id is NULL, which is both realistic and the base case
-- for recursive org-chart queries.
CREATE TABLE employees (
    employee_id    SERIAL       PRIMARY KEY,
    first_name     VARCHAR(100) NOT NULL,
    last_name      VARCHAR(100) NOT NULL,
    email          VARCHAR(255) NOT NULL,
    phone          VARCHAR(40),
    hire_date      DATE         NOT NULL,
    job_title      VARCHAR(120) NOT NULL,
    salary         NUMERIC(12, 2) NOT NULL,
    department_id  INTEGER      NOT NULL,
    manager_id     INTEGER,
    is_active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_employees_email UNIQUE (email),
    CONSTRAINT fk_employees_department
        FOREIGN KEY (department_id) REFERENCES departments (department_id),
    CONSTRAINT fk_employees_manager
        FOREIGN KEY (manager_id) REFERENCES employees (employee_id),
    CONSTRAINT chk_employees_salary_positive CHECK (salary > 0),
    CONSTRAINT chk_employees_not_self_manager
        CHECK (manager_id IS DISTINCT FROM employee_id),
    CONSTRAINT chk_employees_hire_date_sane
        CHECK (hire_date >= DATE '1990-01-01')
);

CREATE TABLE customers (
    customer_id      SERIAL       PRIMARY KEY,
    customer_name    VARCHAR(200) NOT NULL,
    email            VARCHAR(255) NOT NULL,
    phone            VARCHAR(40),
    country          VARCHAR(100) NOT NULL,
    city             VARCHAR(100),
    -- 'individual' or 'business'. Drives business-rule questions where
    -- the two segments are treated differently.
    customer_segment VARCHAR(20)  NOT NULL DEFAULT 'individual',
    -- Credit ceiling for business accounts. NULL for individuals, which is
    -- the intended source of NULL-handling questions.
    credit_limit     NUMERIC(12, 2),
    signup_date      DATE         NOT NULL,
    is_active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_customers_email UNIQUE (email),
    CONSTRAINT chk_customers_segment
        CHECK (customer_segment IN ('individual', 'business')),
    CONSTRAINT chk_customers_credit_limit_non_negative
        CHECK (credit_limit IS NULL OR credit_limit >= 0),
    CONSTRAINT chk_customers_email_format CHECK (email LIKE '%_@_%.__%')
);

CREATE TABLE products (
    product_id     SERIAL       PRIMARY KEY,
    product_name   VARCHAR(250) NOT NULL,
    sku            VARCHAR(64)  NOT NULL,
    category_id    INTEGER      NOT NULL,
    supplier_id    INTEGER,
    -- List price. What an order_item actually charged is stored on the
    -- order_item itself, because list prices change over time.
    unit_price     NUMERIC(12, 2) NOT NULL,
    -- What the product costs us. Enables margin questions.
    unit_cost      NUMERIC(12, 2),
    weight_kg      NUMERIC(10, 3),
    is_discontinued BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_products_sku UNIQUE (sku),
    CONSTRAINT fk_products_category
        FOREIGN KEY (category_id) REFERENCES categories (category_id),
    -- Nullable FK: a discontinued product may outlive its supplier record.
    CONSTRAINT fk_products_supplier
        FOREIGN KEY (supplier_id) REFERENCES suppliers (supplier_id),
    CONSTRAINT chk_products_price_non_negative CHECK (unit_price >= 0),
    CONSTRAINT chk_products_cost_non_negative
        CHECK (unit_cost IS NULL OR unit_cost >= 0),
    CONSTRAINT chk_products_weight_positive
        CHECK (weight_kg IS NULL OR weight_kg > 0)
);


-- =====================================================================
-- SECTION 3 — Transactional tables
-- Highest row counts. These carry most of the analytical workload.
-- =====================================================================

CREATE TABLE orders (
    order_id       SERIAL       PRIMARY KEY,
    customer_id    INTEGER      NOT NULL,
    -- Sales rep who handled the order. NULL for self-service online orders,
    -- which is the main source of "orders with no assigned rep" questions
    -- and of LEFT JOIN vs INNER JOIN mistakes.
    employee_id    INTEGER,
    order_date     TIMESTAMPTZ  NOT NULL,
    required_date  DATE,
    status         VARCHAR(20)  NOT NULL DEFAULT 'pending',
    -- Denormalised order total, kept in sync by the data generator.
    -- Real systems denormalise this for performance; it also creates a
    -- genuine ambiguity for the model: total_amount vs SUM(order_items).
    total_amount   NUMERIC(12, 2) NOT NULL DEFAULT 0,
    shipping_cost  NUMERIC(12, 2) NOT NULL DEFAULT 0,
    currency       CHAR(3)      NOT NULL DEFAULT 'USD',
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_orders_customer
        FOREIGN KEY (customer_id) REFERENCES customers (customer_id),
    CONSTRAINT fk_orders_employee
        FOREIGN KEY (employee_id) REFERENCES employees (employee_id),
    CONSTRAINT chk_orders_status
        CHECK (status IN ('pending', 'processing', 'shipped',
                          'delivered', 'cancelled', 'returned')),
    CONSTRAINT chk_orders_total_non_negative CHECK (total_amount >= 0),
    CONSTRAINT chk_orders_shipping_non_negative CHECK (shipping_cost >= 0)
);

CREATE TABLE order_items (
    order_item_id  SERIAL       PRIMARY KEY,
    order_id       INTEGER      NOT NULL,
    product_id     INTEGER      NOT NULL,
    quantity       INTEGER      NOT NULL,
    -- Price actually charged, captured at order time. Deliberately separate
    -- from products.unit_price: historical orders must not change when a
    -- product is repriced.
    unit_price     NUMERIC(12, 2) NOT NULL,
    discount_pct   NUMERIC(5, 2)  NOT NULL DEFAULT 0,

    -- ON DELETE CASCADE: an order line has no meaning without its order.
    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id) REFERENCES orders (order_id) ON DELETE CASCADE,
    CONSTRAINT fk_order_items_product
        FOREIGN KEY (product_id) REFERENCES products (product_id),
    -- The same product must not appear twice on one order.
    CONSTRAINT uq_order_items_order_product UNIQUE (order_id, product_id),
    CONSTRAINT chk_order_items_quantity_positive CHECK (quantity > 0),
    CONSTRAINT chk_order_items_price_non_negative CHECK (unit_price >= 0),
    CONSTRAINT chk_order_items_discount_range
        CHECK (discount_pct >= 0 AND discount_pct <= 100)
);

-- One order may have several payments (deposit + balance), so "unpaid
-- orders" requires HAVING SUM(amount) < total rather than a simple join.
CREATE TABLE payments (
    payment_id      SERIAL       PRIMARY KEY,
    order_id        INTEGER      NOT NULL,
    payment_date    TIMESTAMPTZ  NOT NULL,
    amount          NUMERIC(12, 2) NOT NULL,
    payment_method  VARCHAR(30)  NOT NULL,
    status          VARCHAR(20)  NOT NULL DEFAULT 'completed',
    transaction_ref VARCHAR(100),

    CONSTRAINT fk_payments_order
        FOREIGN KEY (order_id) REFERENCES orders (order_id) ON DELETE CASCADE,
    CONSTRAINT uq_payments_transaction_ref UNIQUE (transaction_ref),
    CONSTRAINT chk_payments_amount_positive CHECK (amount > 0),
    CONSTRAINT chk_payments_method
        CHECK (payment_method IN ('credit_card', 'debit_card', 'paypal',
                                  'bank_transfer', 'wire', 'cash')),
    CONSTRAINT chk_payments_status
        CHECK (status IN ('pending', 'completed', 'failed', 'refunded'))
);

CREATE TABLE shipments (
    shipment_id     SERIAL       PRIMARY KEY,
    order_id        INTEGER      NOT NULL,
    warehouse_id    INTEGER      NOT NULL,
    shipped_date    TIMESTAMPTZ,
    -- NULL until delivery. The main source of "orders shipped but not yet
    -- delivered" questions, which require IS NULL rather than a comparison.
    delivered_date  TIMESTAMPTZ,
    carrier         VARCHAR(100),
    tracking_number VARCHAR(100),
    status          VARCHAR(20)  NOT NULL DEFAULT 'preparing',

    CONSTRAINT fk_shipments_order
        FOREIGN KEY (order_id) REFERENCES orders (order_id) ON DELETE CASCADE,
    CONSTRAINT fk_shipments_warehouse
        FOREIGN KEY (warehouse_id) REFERENCES warehouses (warehouse_id),
    CONSTRAINT uq_shipments_tracking_number UNIQUE (tracking_number),
    CONSTRAINT chk_shipments_status
        CHECK (status IN ('preparing', 'in_transit', 'delivered',
                          'delayed', 'lost', 'returned')),
    -- Cannot be delivered before it shipped.
    CONSTRAINT chk_shipments_date_order
        CHECK (delivered_date IS NULL
               OR shipped_date IS NULL
               OR delivered_date >= shipped_date)
);

-- Stock level per product per warehouse. The composite unique key is the
-- natural grain: one row per (product, warehouse) pair.
CREATE TABLE inventory (
    inventory_id      SERIAL      PRIMARY KEY,
    product_id        INTEGER     NOT NULL,
    warehouse_id      INTEGER     NOT NULL,
    quantity_on_hand  INTEGER     NOT NULL DEFAULT 0,
    -- Stock level that should trigger a reorder. Enables the classic
    -- "products below reorder level" business-rule question.
    reorder_level     INTEGER     NOT NULL DEFAULT 0,
    last_restocked_at TIMESTAMPTZ,

    CONSTRAINT fk_inventory_product
        FOREIGN KEY (product_id) REFERENCES products (product_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_inventory_warehouse
        FOREIGN KEY (warehouse_id) REFERENCES warehouses (warehouse_id),
    CONSTRAINT uq_inventory_product_warehouse
        UNIQUE (product_id, warehouse_id),
    CONSTRAINT chk_inventory_quantity_non_negative
        CHECK (quantity_on_hand >= 0),
    CONSTRAINT chk_inventory_reorder_non_negative CHECK (reorder_level >= 0)
);


-- =====================================================================
-- SECTION 4 — Indexes
--
-- PostgreSQL indexes PRIMARY KEY and UNIQUE columns automatically, but
-- NOT foreign key columns. Joins across those columns dominate this
-- workload, so each one gets an explicit index. Date and status columns
-- are indexed because nearly every benchmark question filters on them.
-- =====================================================================

-- Foreign keys
CREATE INDEX idx_categories_parent      ON categories (parent_category_id);
CREATE INDEX idx_employees_department   ON employees (department_id);
CREATE INDEX idx_employees_manager      ON employees (manager_id);
CREATE INDEX idx_products_category      ON products (category_id);
CREATE INDEX idx_products_supplier      ON products (supplier_id);
CREATE INDEX idx_orders_customer        ON orders (customer_id);
CREATE INDEX idx_orders_employee        ON orders (employee_id);
CREATE INDEX idx_order_items_order      ON order_items (order_id);
CREATE INDEX idx_order_items_product    ON order_items (product_id);
CREATE INDEX idx_payments_order         ON payments (order_id);
CREATE INDEX idx_shipments_order        ON shipments (order_id);
CREATE INDEX idx_shipments_warehouse    ON shipments (warehouse_id);
CREATE INDEX idx_inventory_product      ON inventory (product_id);
CREATE INDEX idx_inventory_warehouse    ON inventory (warehouse_id);

-- Common filter columns
CREATE INDEX idx_orders_order_date      ON orders (order_date);
CREATE INDEX idx_orders_status          ON orders (status);
CREATE INDEX idx_customers_country      ON customers (country);
CREATE INDEX idx_customers_segment      ON customers (customer_segment);
CREATE INDEX idx_payments_payment_date  ON payments (payment_date);
CREATE INDEX idx_shipments_status       ON shipments (status);
CREATE INDEX idx_suppliers_country      ON suppliers (country);


-- =====================================================================
-- SECTION 5 — Column documentation
--
-- COMMENT ON is stored in the database itself, so Phase 5 schema
-- retrieval can read these back and show the model what an ambiguous
-- column actually means. Only genuinely non-obvious columns are
-- documented; commenting `customer_name` would be noise.
-- =====================================================================

COMMENT ON COLUMN categories.parent_category_id IS
    'Parent category, NULL for top-level categories. Self-referencing hierarchy.';
COMMENT ON COLUMN employees.manager_id IS
    'This employee''s manager, NULL for the top of the org chart.';
COMMENT ON COLUMN customers.customer_segment IS
    'Either individual or business. Business customers may have a credit_limit.';
COMMENT ON COLUMN customers.credit_limit IS
    'Maximum outstanding balance allowed. NULL for individual customers.';
COMMENT ON COLUMN products.unit_price IS
    'Current list price. Historical sale prices live on order_items.unit_price.';
COMMENT ON COLUMN products.unit_cost IS
    'Cost to acquire the product. Revenue minus cost gives margin.';
COMMENT ON COLUMN orders.employee_id IS
    'Sales representative handling the order. NULL for self-service online orders.';
COMMENT ON COLUMN orders.total_amount IS
    'Denormalised order total including shipping. Should equal the sum of its '
    'order_items after discount, plus shipping_cost.';
COMMENT ON COLUMN order_items.unit_price IS
    'Price charged at the time of sale, not the product''s current list price.';
COMMENT ON COLUMN order_items.discount_pct IS
    'Percentage discount, 0-100. Line revenue is '
    'quantity * unit_price * (1 - discount_pct / 100).';
COMMENT ON COLUMN shipments.delivered_date IS
    'When the shipment reached the customer. NULL if not yet delivered.';
COMMENT ON COLUMN inventory.reorder_level IS
    'Stock threshold below which the product should be reordered.';

COMMIT;
